### ISSUE TITLE
Vulnerabilities | Host IP address hard coded in PHP script

### ISSUE THREAD

**Issue by Vishwasena-Raidu-Nyaramneni** [anveshmuppeda/docker-login-page#10]
In index1.php file, the host IP address is hard coded. Hardcoding sensitive information like IP addresses can pose security risks.

**Comment by saimanasak** [comment]
Solved the issue.

**Comment by Vishwasena-Raidu-Nyaramneni** [comment]
Host IP address is removed from php files.
